from __future__ import annotations

UI_COMPONENT_EXPORTS = (
    "ActionButton",
    "AppFrame",
    "AppShell",
    "Badge",
    "Card",
    "CommandPalette",
    "Dialog",
    "EmptyState",
    "FeedbackToast",
    "FocusScope",
    "ListRow",
    "Menu",
    "MetricTile",
    "NavItem",
    "RouteView",
    "SectionHeader",
    "Select",
    "SidebarFrame",
    "SidebarItem",
    "SidebarNav",
    "StatCard",
    "StatusPill",
    "Surface",
    "TabButton",
    "Tabs",
    "Toast",
    "TopBar",
    "Toolbar",
)

UI_DYNAMIC_CLASS_CANDIDATES = (
    "is-active",
    "is-danger",
    "is-default",
    "is-disabled",
    "is-full",
    "is-ghost",
    "is-good",
    "is-horizontal",
    "is-info",
    "is-lg",
    "is-md",
    "is-neutral",
    "is-primary",
    "is-secondary",
    "is-sm",
    "is-soft",
    "is-success",
    "is-vertical",
    "is-warn",
    "max-w-5xl",
    "max-w-6xl",
    "max-w-7xl",
    "max-w-full",
)
